import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import { authenticate } from "../middlewares/auth.js";
import authRouter from "./auth.js";
import residentsRouter from "./residents.js";
import itemsRouter from "./items.js";
import pricingRouter from "./pricing.js";
import ordersRouter from "./orders.js";
import vendorsRouter from "./vendors.js";
import ridersRouter from "./riders.js";
import adminRouter from "./admin.js";
import storageRouter from "./storage.js";
import deliveryPartnersRouter from "./deliveryPartners.js";
import blockGroupsRouter from "./blockGroups.js";
import agentsRouter from "./agents.js";
import complaintsRouter from "./complaints.js";
import financeRouter from "./finance.js";
import employeesRouter from "./employees.js";
import expensesRouter from "./expenses.js";
import floatRouter from "./float.js";
import payrollRouter from "./payroll.js";
import paymentsRouter from "./payments.js";
import gatewaySettingsRouter from "./gatewaySettings.js";
import paystackWebhookRouter from "./paystackWebhook.js";
import riderMessagesRouter from "./riderMessages.js";
import vendorMessagesRouter from "./vendorMessages.js";
import vendorStatsRouter from "./vendor.js";
import adminAccountsRouter from "./adminAccounts.js";
import estatesRouter from "./estates.js";
import agentMessagesRouter from "./agentMessages.js";
import notificationsRouter from "./notifications.js";
import payoutsRouter from "./payouts.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
// Note: /residents has both public (signup, estates list) and protected routes.
// Auth is applied per-route inside residents.ts — do NOT gate the whole subtree here.
router.use("/residents", residentsRouter);
router.use("/items", itemsRouter);
router.use("/pricing", pricingRouter);
router.use("/orders", authenticate, ordersRouter);
router.use("/vendors", vendorsRouter);
router.use("/riders", ridersRouter);
router.use("/admin", adminRouter);
router.use("/storage", storageRouter);
router.use("/delivery-partners", deliveryPartnersRouter);
router.use("/block-groups", blockGroupsRouter);
router.use("/agents", agentsRouter);
router.use("/complaints", complaintsRouter);
router.use("/finance", financeRouter);
router.use("/employees", employeesRouter);
router.use("/expenses", expensesRouter);
router.use("/float", floatRouter);
router.use("/payroll", payrollRouter);
router.use("/payments", paymentsRouter);
router.use("/settings/gateway", gatewaySettingsRouter);
router.use("/paystack/webhook", paystackWebhookRouter);
router.use("/rider-messages", riderMessagesRouter);
router.use("/vendor-messages", vendorMessagesRouter);
router.use("/vendor", vendorStatsRouter);
router.use("/admin-accounts", adminAccountsRouter);
router.use("/estates", estatesRouter);
router.use("/agent-messages", agentMessagesRouter);
router.use("/notifications", notificationsRouter);
router.use("/payouts", payoutsRouter);

export default router;
