import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import residentsRouter from "./residents";
import itemsRouter from "./items";
import pricingRouter from "./pricing";
import ordersRouter from "./orders";
import vendorsRouter from "./vendors";
import ridersRouter from "./riders";
import adminRouter from "./admin";
import storageRouter from "./storage";
import deliveryPartnersRouter from "./deliveryPartners";
import blockGroupsRouter from "./blockGroups";
import agentsRouter from "./agents";
import complaintsRouter from "./complaints";
import financeRouter from "./finance";
import employeesRouter from "./employees";
import expensesRouter from "./expenses";
import floatRouter from "./float";
import payrollRouter from "./payroll";
import paymentsRouter from "./payments";
import gatewaySettingsRouter from "./gatewaySettings";
import riderMessagesRouter from "./riderMessages";
import vendorMessagesRouter from "./vendorMessages";
import vendorStatsRouter from "./vendor";
import adminAccountsRouter from "./adminAccounts";
import estatesRouter from "./estates";
import agentMessagesRouter from "./agentMessages";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/residents", residentsRouter);
router.use("/items", itemsRouter);
router.use("/pricing", pricingRouter);
router.use("/orders", ordersRouter);
router.use("/vendors", vendorsRouter);
router.use("/riders", ridersRouter);
router.use("/admin", adminRouter);
router.use("/storage", storageRouter);
router.use("/delivery-partners", deliveryPartnersRouter);
router.use("/block-groups", blockGroupsRouter);
router.use("/agents", agentsRouter);
router.use("/complaints", complaintsRouter);
router.use("/finance", financeRouter);
router.use("/employees", employeesRouter);
router.use("/expenses", expensesRouter);
router.use("/float", floatRouter);
router.use("/payroll", payrollRouter);
router.use("/payments", paymentsRouter);
router.use("/settings/gateway", gatewaySettingsRouter);
router.use("/rider-messages", riderMessagesRouter);
router.use("/vendor-messages", vendorMessagesRouter);
router.use("/vendor", vendorStatsRouter);
router.use("/admin-accounts", adminAccountsRouter);
router.use("/estates", estatesRouter);
router.use("/agent-messages", agentMessagesRouter);

export default router;
